config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tasks_users, only: [:create]
  resources :user_workspaces
  root 'welcome#index'
  put '/tasks/:id' => 'tasks#update_list'
  match "/invite_user" => "users#invite", :via => :post, :as => :invite_user
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users, only: %i[index, destroy, create]
  resources :plans, only: [:index]
  resources :boards, only: %i[index show create destroy update]
  resources :charges, only: %i[create]
  resources :tasks, only: %i[create update]
  resources :lists, only: %i[create destroy]
  resources :users do
    member do
      get :confirm_email
    end
  end
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  belongs_to :board
  has_many :tasks, dependent: :destroy
  validates :name, presence: true, length: { minimum: 1, maximum: 25 }
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  before_action :set_list, only: [:destroy]
  before_action :set_board, only: [:create]

  def destroy
    @board = @list.board
    @list.destroy
    flash[:notice] = 'The list and its tasks were deleted'
    redirect_to @board
  end

  def create
    @list = List.new(list_params)
    if @list.save
    else
      flash[:danger] = 'Something went wrong.'
    end
    redirect_to @board
  end

  private

  def set_board
    @board = Board.find_by(id: list_params[:board_id])
  end

  def set_list
    @list = List.find_by(id: params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :board_id)
  end
end

app/views/lists/_new.html.erb
<div class="col">
  <div> 
    <button class="bg-light rounded px-4 py-2 d-flex border-0" id="add_list_button" style="width: 18rem;">
      Add a list
    </button>
  </div>

  <div class="bg-light p-3 rounded" id="form_new_list" style="width: 18rem;">
    <%= form_with scope: :list, url: lists_path, local: true do |f| %>
      <form>
        <div class="mb-2">
          <%= f.text_field :name, placeholder: "Introduce a name for this list", class:"rounded-1 form-control h-16"%>
        </div>
        <div>
          <%= f.text_field :board_id, type: "hidden", value: board.id %>
        </div>
        <%= f.submit 'submit', class: 'btn btn-primary rounded-1'%>
        <a href="#" class='btn btn-close rounded-1' id="close_form">
        </a>
      </form>
    <% end %>
  </div>
</div>

<%= javascript_pack_tag "new_list" %> 

app/views/lists/_show.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h4 class="mt-3 px-2"><%= list.name %></h4>
  <div class="dropdown">
    <div data-bs-toggle="dropdown" aria-expanded="false">
      <%= embedded_svg('ellipsis-solid', class:"svg-icon") %>
    </div>
    <ul class="dropdown-menu">
      <li><a class="dropdown-item" href="#">Rename</a></li>
      <li>
        <%= link_to "Delete", list_path(list.id), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure?"} %>
      </li>
    </ul>
  </div>
</div>

<ul class="unorder_list mt-3 list list-group d-flex gap-2" style="min-height: 20px;" id="<%= list.id%>">
  <% list.tasks.each do |task| %>
    <li class="task-item list-group-item rounded-1 border-0 shadow-sm" data-bs-toggle="modal" data-bs-target="#modalContainer<%=task.id%>" id="<%=task.id%>">
      <%= task.title %>
    </li>
    <div class="modal fade" id="modalContainer<%=task.id%>" tabindex="-1" aria-hidden="true">
      <%=render(:partial => "tasks/show", :locals => {:task => task})%>
    </div>
  <% end %>
</ul>

<div class="hidden my-3" id="add_<%= list.id%>">
  <a href="#" class="add rounded-1 p-2 text-decoration-none text-muted">
    Add a new task
  </a>
</div>

<div class="hidden my-3" id="form_<%= list.id%>" style="display: none;">
  <%= render(:partial => "tasks/new", :locals => {:list => list})%>
</div>