config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tasks_users, only: [:create]
  resources :user_workspaces
  root 'welcome#index'
  put '/tasks/:id' => 'tasks#update_list'
  match "/invite_user" => "users#invite", :via => :post, :as => :invite_user
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users, only: %i[index, destroy, create]
  resources :plans, only: [:index]
  resources :boards, only: %i[index show create destroy update]
  resources :charges, only: %i[create]
  resources :tasks, only: %i[create update]
  resources :lists, only: %i[create destroy]
  resources :users do
    member do
      get :confirm_email
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_workspaces
  has_many :workspaces, through: :user_workspaces, dependent: :delete_all
  has_many :tasks_users
  has_many :users, through: :tasks_users
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:destroy]
  def index
    @workspace = current_user.workspaces.first
    @users = @workspace.users
  end

  def create
    byebug
  end

  def destroy
    if @user.destroy
      flash[:notice] = 'User deleted successfully.'
      redirect_to users_path
    else
      flash[:danger] = 'Something went wrong'
      redirect_to users_path
    end
  end

  def invite
    email = params[:users][:email]
    if user = User.invite!({:email => email}, current_user)
      current_workspace.users << user
      flash[:notice] = 'User invited successfully.'
      redirect_to users_path
    else
      flash[:danger] = 'Something went wrong.'
      redirect_to users_path
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_add_to_workspace.html.erb
<div class="modal fade" id="add_user_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
  <div class="modal-content">
    <div class="modal-header">
      <h1 class="modal-title fs-5" id="exampleModalLabel">Add a new user to your worspace</h1>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <%= form_with scope: :users, url: invite_user_path, local: true do |f| %>
        <div class="modal-body">
          <div class="mb-3">
            <%= f.label :email, class:"form-label" %><br />
            <%= f.text_field :email, placeholder: "email@example.com", class:"form-control"%>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.submit 'Send invitation', class: 'btn btn-primary rounded-1'%>
        </div>
      </form>
    <% end %>
  </div>
</div>
</div>

app/views/users/index.html.erb
<div>
  <div class="w-100" >
  </div>
</div>

<div class="container">
  <div class="d-flex align-items-center gap-5 mt-5">
    <div>
      <h3 class="m-0">Workspace Members</h1>
      <p class="m-0 text-muted" style="padding-left:5px;">Manage your team members here</p>
    </div>
    <div>
      <button type="button" class="btn btn-outline-dark d-flex gap-2 align-items-center" data-bs-toggle="modal" data-bs-target="#add_user_modal">
        <%= embedded_svg('plus-solid', class:"svg-add-icon") %>
        Add workspace member
      </button>
    </div>
  </div>

  <div>
    <table class="table w-50">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">email</th>
          <th scope="col">Invitation status</th>
          <th scope="col">Date invited</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <%=@users.each do |user| %>
          <tr>
            <td><%=complete_name(user)%></td>
            <td><%=user.email%></td>
            <% if user == current_user %>
              <td>-</td>
            <% else %>
              <td><%=user.invitation_accepted?%></td>
            <% end %>
            <td><%=format_date(user.created_at)%></td>
            <td>
              <%= link_to user_path(user), method: :delete, data: {confirm: "Are you sure?"} do %>
                <%= embedded_svg('trash-can', class:"svg-icon") %>
              <%end%>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

<%= render 'users/add_to_workspace'%>