config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tasks_users, only: [:create]
  resources :user_workspaces
  root 'welcome#index'
  put '/tasks/:id' => 'tasks#update_list'
  match "/invite_user" => "users#invite", :via => :post, :as => :invite_user
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users, only: %i[index, destroy, create]
  resources :plans, only: [:index]
  resources :boards, only: %i[index show create destroy update]
  resources :charges, only: %i[create]
  resources :tasks, only: %i[create update]
  resources :lists, only: %i[create destroy]
  resources :users do
    member do
      get :confirm_email
    end
  end
end

app/models/plan.rb
# frozen_string_literal: true

class Plan < ApplicationRecord
  monetize :price_cents
end

app/controllers/plans_controller.rb
# frozen_string_literal: true

class PlansController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @plans = Plan.all
  end
end

app/views/plans/index.html.erb
<div class="container mt-5">
  <h1 class="text-center">Get started</h1>
  <p class="text-center text-muted">Choose a plan tailored to your needs</p>
  <div class="row justify-content-around">
    <% @plans.each do |plan| %>
      <div class="col mt-4">
        <div class="card py-2 border-0 shadow rounded-4" style="height: 540px;">
          <div class="card-body d-flex flex-column gap-4">
            <div>
              <h5 class="card-title fs-3">
                <%=plan.name%>
              </h5>
              <p class="text-sm-start text-muted"><%=plan.description%></p>
            </div>
            <p><strong class="fs-1"><%=money_translate(plan)%></strong> per/month</p>
            <%= form_tag charges_path do %>
              <article>
                <% if flash[:error].present? %>
                  <div id="error_explanation">
                    <p><%= flash[:error] %></p>
                  </div>
                <% end %>
              </article>
            
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= get_key() %>"
                      data-description="A month's subscription"
                      data-amount="<%=plan.price_cents%>"
                      data-locale="auto"></script>
            <% end %>
            <div class="mt-4">
              <p>Lite includes:</p>
              <ul class="plan-features-list">
                <li class="plan-feature">50 accounts</li>
                <li class="plan-feature">10 boards</li>
                <li class="plan-feature">CMS integration</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>