config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tasks_users, only: [:create]
  resources :user_workspaces
  root 'welcome#index'
  put '/tasks/:id' => 'tasks#update_list'
  match "/invite_user" => "users#invite", :via => :post, :as => :invite_user
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users, only: %i[index, destroy, create]
  resources :plans, only: [:index]
  resources :boards, only: %i[index show create destroy update]
  resources :charges, only: %i[create]
  resources :tasks, only: %i[create update]
  resources :lists, only: %i[create destroy]
  resources :users do
    member do
      get :confirm_email
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-center text-white">
  <div class="container p-4 pb-0">
  <section class="">
  <p class="d-flex justify-content-center align-items-center">
    <span class="me-3">Register for free</span>
    <button type="button" class="btn btn-outline-light btn-rounded">
      Sign up!
    </button>
  </p>
</section>
  </div>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    TManager
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
   <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
       <%= msg %>
       <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
     </div>
   <% end %> 
 </div> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">TManagement</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link"%>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Boards', boards_path, class: "nav-link"%>
          </li>
          <% if current_user.role == "manager" %>
            <li class="nav-item">
              <%= link_to 'Members', users_path, class: "nav-link"%>
            </li>
          <%end%>
        <%else%>
          <li class="nav-item">
            <%= link_to 'Pricing', plans_path, class: "nav-link"%>
          </li>
        <% end %>

      </ul>
      <% if user_signed_in? %>
        <div class="btn-group dropstart">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Account
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
          </ul>
        </div>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="box">
      <div class="somerow header">
        <%= render 'layouts/navigation' %>
      </div>
      <div class="somerow content">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
      <div class="somerow footer">
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>